# Generated by Django 4.2.5 on 2023-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerCapacity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eic", models.CharField()),
                ("name", models.CharField()),
                ("output", models.CharField()),
                ("source", models.CharField()),
            ],
        ),
    ]
