# Generated by Django 4.2.5 on 2023-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_plants", "0003_powerproduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerproduction",
            name="name",
            field=models.CharField(default="unknown"),
            preserve_default=False,
        ),
    ]
