# Generated by Django 4.2.5 on 2023-11-26 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_plants", "0005_powermix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("gid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nom", models.CharField()),
                ("wikipedia", models.CharField()),
                ("code_insee", models.CharField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
                ),
            ],
            options={
                "verbose_name": "région",
                "db_table": "osm_regions",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="powerplant",
            options={"managed": False, "verbose_name": "centrale"},
        ),
        migrations.AddField(
            model_name="powermix",
            name="insee_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
