# Generated by Django 4.2.14 on 2024-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_plants", "0006_region_alter_powerplant_options_powermix_insee_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantRegion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("region_id", models.BigIntegerField()),
                ("plant_id", models.BigIntegerField()),
            ],
        ),
    ]
