# Generated by Django 4.2.14 on 2024-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("power_plants", "0007_plantregion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantEic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eic", models.CharField()),
                ("plant_id", models.BigIntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name="powerplant",
            table="power_plants",
        ),
    ]
