export const hydroLayers = [
  {
    id: "power_plants_area_hydro",
    source: "parc_elec",
    "source-layer": "power_plants",
    type: "fill",
    minzoom: 10,
    filter: ["==", "source", "hydro"],
    paint: {
      "fill-antialias": true,
      "fill-color": "#198EC8",
      "fill-opacity": 0.5,
    },
  },
  {
    id: "power_plants_outline_hydro",
    source: "parc_elec",
    "source-layer": "power_plants",
    type: "line",
    minzoom: 10,
    filter: ["==", "source", "hydro"],
    paint: {
      "line-width": 3,
      "line-color": "#198EC8",
    },
  },
  {
    id: "power_plants_circle_hydro",
    source: "parc_elec",
    "source-layer": "power_plants_name",
    type: "circle",
    filter: ["==", "source", "hydro"],
    paint: {
      "circle-color": "#198EC8",
      "circle-radius": 3,
    },
  },
  {
    id: "power_plants_icon_hydro",
    source: "parc_elec",
    "source-layer": "power_plants_name",
    type: "symbol",
    minzoom: 10,
    filter: ["==", "source", "hydro"],
    layout: {
      "icon-allow-overlap": true,
      "icon-image": "water",
      "icon-size": ["interpolate", ["linear"], ["zoom"], 10, 0.6, 18, .8],
    },
  },
  {
    id: "power_plants_name_hydro",
    source: "parc_elec",
    "source-layer": "power_plants_name",
    type: "symbol",
    minzoom: 10,
    filter: ["==", "source", "hydro"],
    layout: {
      "symbol-placement": "point",
      "text-field": "{name}",
      "text-offset": [0, 1.7],
      "text-size": ["interpolate", ["linear"], ["zoom"], 10, 11, 18, 13],
      "text-anchor": "top",
      "text-keep-upright": true,
      "text-max-angle": 45,
      "text-font": ["Source Sans Pro Bold Italic"],
    },
    paint: {
      "text-halo-color": "#fff",
      "text-halo-width": 1,
    },
  },
];
