[[providers]]
name = "postgis"
type = "mvt_postgis"
uri = "postgresql://postgres@localhost:5432/osm"
srid = 3857

[[providers.layers]]
name = "power_plants"
sql = """
SELECT
  osm_id as gid,
  name,
  source,
  normalize_power(output)::bigint as output,
  ST_AsMVTGeom(ST_SimplifyPreserveTopology(geometry, !PIXEL_WIDTH! / 4), !BBOX!) as geom
FROM osm_power_plants
WHERE geometry && !BBOX! AND name != ''
"""
geometry_type = "Polygon"

[[providers.layers]]
name = "power_plants_name"
sql = """
SELECT
  osm_id as gid,
  name,
  source,
  normalize_power(output)::bigint as output,
  ST_AsMVTGeom(ST_Centroid(geometry), !BBOX!) AS geom
FROM osm_power_plants
WHERE geometry && !BBOX! AND name != ''
"""
geometry_type = "Point"

[[maps]]
name = "parc-elec"
center = [ 0.0, 0.0, 2.0,]

[[maps.layers]]
provider_layer = "postgis.power_plants"

[[maps.layers]]
provider_layer = "postgis.power_plants_name"